#!/usr/bin/env node
// npm run context — _context/structure.md for the previews site: one section per lead,
// generated by the template's context script with CONTENT_ROOT pointed at that lead.
import { readdirSync, existsSync, statSync, writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';

const ROOT = new URL('..', import.meta.url).pathname.replace(/\/$/, '');
const LEADS = join(ROOT, 'src/content/leads');
const slugs = existsSync(LEADS) ? readdirSync(LEADS).filter((d) => !d.startsWith('_') && statSync(join(LEADS, d)).isDirectory()).sort() : [];
const out = ['# Previews site structure', '', `_Generated by \`npm run context\` on ${new Date().toISOString().slice(0, 10)}. Do not edit._`, '', `${slugs.length} lead preview(s). Each lead is a folder under \`src/content/leads/<slug>/\` with the template page shape; routes are \`/<slug>/\` and \`/<slug>/<page>/\`.`, ''];
for (const slug of slugs) {
  execFileSync('node', [join(ROOT, 'scripts/context-one.mjs')], { env: { ...process.env, CONTENT_ROOT: `src/content/leads/${slug}` } });
  const one = readFileSync(join(ROOT, '_context/structure.md'), 'utf8').split('\n').slice(3).join('\n').replace(/^## /gm, '### ').replace(/^# /gm, '## ');
  out.push(`## ${slug} — \`/${slug}/\``, '', one.replace(/\| `\/(.*?)` \|/g, (m, r) => `| \`/${slug}/${r === '' ? '' : r}\` |`).replaceAll('src/content/pages/', `src/content/leads/${slug}/pages/`).replaceAll('src/content/globals/', `src/content/leads/${slug}/globals/`), '');
}
mkdirSync(join(ROOT, '_context'), { recursive: true });
writeFileSync(join(ROOT, '_context/structure.md'), out.join('\n'));
console.log(`✓ _context/structure.md — ${slugs.length} lead(s)`);
